### ISSUE TITLE
crash on start( i3 tiling wm linux)

### ISSUE THREAD

**Issue by Spear5030** [axcore/axmud#1]
After start shows only main window with logo(loading) and crashs with message:

> PERL ERROR: Can't call method "get_neighbor" on an undefined value at /usr/share/perl5/Games/Axmud/Obj/Desktop.pm line 635.
> Can't call method "get_neighbor" on an undefined value at /usr/share/perl5/Games/Axmud/Obj/Desktop.pm line 635.
PERL WARNING: Gtk-CRITICAL **: IA__gtk_main_quit: assertion 'main_loops != NULL' failed at /usr/share/perl5/Games/Axmud/Client.pm line 6809.

**Comment by axcore** [comment]
I was unable to reproduce this error.

I created a fresh installation of Ubuntu, then installed i3wm. Then I installed Axmud using the .DEB file, which worked as expected. 

I also installed Axmud from source code, using the procedure described in the INSTALL file.

[https://imgur.com/a/kWcTwIn](url)

Which Linux distro are you using? How did you install Axmud (.DEB, .RPM, source code...?)
