### ISSUE TITLE
Complex maps

### ISSUE THREAD

**Issue by mdr55** [axcore/axmud#10]
For more complex maps I'm seeing various warnings popping up (not always the same, but sofar almost always non-fatal).  It doesn't seem to correlate to purely number of rooms, it seems to be some combination of multiple one-way exits, possibly parallel paths in same region, and lots of up/downs.  There's two maps in particular that I'm going to have a try at remapping - just starting with the simpler elements, and then add in the awkward rooms after and see if I can find a trigger.

Do you have any advice on what are the more challenging scenarios for the code to handle?  Also is it useful if I drop the warning msgs in this issue?

**Comment by mdr55** [comment]
I have a suspicion that use of retracing exit type (esp if there's two of them in the same room) can cause the following warning message under some circumstances.
WARNING: GLib-GObject-WARNING **: value "-4.000000" of type 'gdouble' is invalid or out of range for property 'height' of type 'gdouble' at /usr/local/share/perl/5.30.0/Games/Axmud/Win/Map.pm line 39841.

**Comment by axcore** [comment]
> WARNING: GLib-GObject-WARNING **: value "-4.000000" of type 'gdouble' is invalid or out of range

This is a debug message for developers of the graphics libraries. We are assured that it's nothing to worry about.

Where is the message appearing? If it's appearing in your system's terminal window, then we can forget about it. If it's appearing inside an Axmud window then we can add code to intercept it.

The message you quoted above is caused by a region exit (connecting two rooms in different regions), which I can tell from the line number.

**Comment by axcore** [comment]
>Do you have any advice on what are the more challenging scenarios for the code to handle?

The existing code ought to be able to handle any scenario (unless it's something which simply never occurred to me). If you can't work out how to draw something, then by all means ask here and we can find a solution.

Presumably you've seen the [Axmud Guide](https://axmud.sourceforge.io/share/docs/guide/ch15.html) which explains how to cope with some arkward mapping situations.

**Comment by mdr55** [comment]
Cheers.   That particular debug message is popping up inside the main axmud window, maybe it can be squelched for the next rev :)  I'll ignore the terminal window errors and put in a ticket here if I see more of the GLib type debug messages in the main window.

**Comment by axcore** [comment]
Reopened so I don't forget to do it.

**Comment by mdr55** [comment]
Can confirm this is fixed, the map that previously had the warning msgs now no longer have them.
edit: sending you the maps for reference via email
