### ISSUE TITLE
Minor - this warning came up a number of times in the main window

### ISSUE THREAD

**Issue by mdr55** [axcore/axmud#11]
WARNING: GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.

Consider suppressing if its a non-issue in next rev?

more info:
seems to be associated with a freshly created one way down exit (or at least it seems to trigger it).  I moved the down room back up one level for presentation purposes and a bunch of these sprang up.  This repeats if I moved that particular room around on the automapper.

I think it somehow fixes itself afterwards though.

**Comment by axcore** [comment]
Should be fixed in v1.3.029.
