### ISSUE TITLE
Minor -  GUI presentation in a window

### ISSUE THREAD

**Issue by mdr55** [axcore/axmud#13]
the involuntary exit pattern sub tab (page 2) in "edit room model object" window has a guidance sentence in italics - something like "Patterns which mean the character...."

This guidance letter doesn't disappear after adding an involuntary exit pattern and is displayed on top of the new entry, making it difficult to read.

**Comment by axcore** [comment]
Ok noted

**Comment by axcore** [comment]
It's another typo. If you don't want to wait for the next full release, you can replace the file **../lib/Games/AxmudEditWin.pm/** with the one I uploaded to Git today.
