### ISSUE TITLE
Can't setup automapper because there is not enough lines

### ISSUE THREAD

**Issue by rinart73** [axcore/axmud#15]
I'm playing Sundering Shadows.

Here is an example of room description. Please note the empty lines.
```
Gwydion Street, Tabor
You are on Gwydion Street in Tabor just east of Mathowvy Road.  Here you
can easily make out the fortress of Caer Tabor on Mount Tabor to the
north and see Mathowvy Road wind up the slope.  To your south, you can
see the great edifice of the Royal Bank of Tabor and you can enter
through a side entrance here.  A most unusual building is just to 
the north, complete with onion-shaped windows and textured walls.  It 
seems to be a tailor of sorts.

Gwydion Street continues to the east and west.
 
The slightly rank scent of a busy city lingers in the air.
You hear the busy sounds of a large town.
It is partly cloudy.

There are four obvious exits: west, east, south, and north.

A dark street light is here.

->
```
Even if I max out (15) the amount of lines in the Locator wizard, there will be enough enough lines.
Here is what Locator wizard sees:
```
1: through a side entrance here.  A most unusual building is just to 
2: the north, complete with onion-shaped windows and textured walls.  It 
3: seems to be a tailor of sorts.
4: 
5: Gwydion Street continues to the east and west.
6: 
7: The slightly rank scent of a busy city lingers in the air.
8: You hear the busy sounds of a large town.
9: It is clear.
10: 
11: There are four obvious exits: west, east, south, and north.
12: 
13: A dark street light is here.
14: 
15: ->
```
So basically when MUD has long room descriptions on multiple lines setting automapper is impossible.

**Comment by axcore** [comment]
The first thing to say is that capturing the description is optional. The automapper only _needs_ to capture the exit list; everything else can be ignored, the automapper will work perfectly well without it.

Do you actually need to capture the whole description (perhaps for archive purposes)? If so, then consider this:

Capturing the whole description is a tricky business. On some MUDs it's easy, on other impossible. On most MUDs it's just a bit tricky.

I walked around Sundering Shadows for a bit and noticed that the verbose description is mostly white, and is preceded by the brief description in green. That would be easy enough to handle, but then I noticed that in some rooms (outside the start town) the description is in green, too.

I'm willing to have a crack at setting everything up for you, but only if you actually need it. (You can tell me if you actually need it).

About the locator wizard: I can change the line limit for the next release. If you like, you can just tweak it yourself: in ../lib/Games/Axmud/WizWin.pm, it's line 2170.

`            analysisMaxLength           => 15,`

Change 15 to any value up to an absolute maximum of 256. (Perhaps 32 would be a good limit for you).

**Comment by rinart73** [comment]
I assumed that capturing room name is also important because some other automappers require it, that's why I needed more lines.

> I'm willing to have a crack at setting everything up for you, but only if you actually need it.

No thank you, I'm fine.

**Comment by axcore** [comment]
v2.0.0, released today, increases the maximum lines to 256. Which should be enough for any eventuality. Sorry for the long delay.
