### ISSUE TITLE
[Info Only] AUR package for Arch Linux

### ISSUE THREAD

**Issue by pezz** [axcore/axmud#3]
Hey there,

I just wanted to let you know that I have created a PKGBUILD for Axmud and it is now available in the AUR:

https://aur.archlinux.org/packages/axmud/

I've also created a desktop file and made use of dialogue_icon_large.png so that it appears in the launcher for various desktop environments (e.g. GNOME Shell).

Cheers and thanks for this excellent client.

**Comment by axcore** [comment]
Wow, that's great! AUR has been on my list of things to do for a long time now.

Regarding desktop files, the one I use for the DEB and RPM installers is in ../axmud/pack.

**Comment by pezz** [comment]
Gotcha, I'll update my PKGBUILD when I get the chance and use yours.

Cheers mate.
