### ISSUE TITLE
How does one set up automatic session logging

### ISSUE THREAD

**Issue by Joxtur** [axcore/axmud#5]
Hi -

One of the features I use in most mud clients is session logging, where all keystrokes and output from the mud log to a single file as plain text. In other platforms I can also automatically choose the output directory and file naming pattern, like Documents/character-20210304.txt.  I was unable to find this in the Guide.

How can one set this up in axmud? I am on linux (CentOS 7)

- Joxtur

**Comment by axcore** [comment]
There are two sets of logs - one produced by the client, and one produced by the session.

To turn on logging in general, click **Edit > Axmud preferences... > Logs > Page 1**, and select **Enable logging in general.** You can't change the filepath (all data, including logs, is written to Axmud's data folder) but you can add a date/time to the filename.

In the same window, click **Page 4** to see the logfiles written by the client. If you are connected to 3 different MUDs at the same time, text from all three is written to the same logfile[s].

For the logs of each session, click **Edit > Edit current world... > Settings > Page 12**.
