### ISSUE TITLE
Phantom rooms?

### ISSUE THREAD

**Issue by mdr55** [axcore/axmud#9]
for some reason a few rooms in an existing map didn't render and automapper was getting lost saying room titles don't match.  I couldn't delete those rooms (can't select them) so I just recreated rooms around it.  
The space on the grid where these unrendered rooms remain however unusable; can't put a room in them.

**Comment by axcore** [comment]
What's the status of this issue, now that you have used ;testmodel successfully?

**Comment by mdr55** [comment]
I think there's enough to close this issue.  I moved the rooms away and didn't exactly mark out where the phantom blocks were.  However, there were 4 blocks and that matched up with 4 errors the ;testmodel fix messages, and when I swept the rough area where the phantom blocks were, they were gone. cheers!
